# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pagseguro}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nando Vieira"]
  s.date = %q{2010-10-16}
  s.description = %q{}
  s.email = %q{fnando.vieira@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".rspec",
     "Gemfile",
     "Gemfile.lock",
     "README.markdown",
     "Rakefile",
     "lib/pagseguro.rb",
     "lib/pagseguro/action_controller.rb",
     "lib/pagseguro/developer_controller.rb",
     "lib/pagseguro/generator.rb",
     "lib/pagseguro/helper.rb",
     "lib/pagseguro/notification.rb",
     "lib/pagseguro/order.rb",
     "lib/pagseguro/railtie.rb",
     "lib/pagseguro/rake.rb",
     "lib/pagseguro/routes.rb",
     "lib/pagseguro/version.rb",
     "lib/pagseguro/views/_form.html.erb",
     "lib/tasks/pagseguro.rake",
     "pagseguro.gemspec",
     "spec/controllers/developer_controller_spec.rb",
     "spec/helpers/helper_spec.rb",
     "spec/pagseguro/notification_spec.rb",
     "spec/pagseguro/order_spec.rb",
     "spec/pagseguro/pagseguro_spec.rb",
     "spec/pagseguro/rake_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/app/controllers/application_controller.rb",
     "spec/support/app/models/account.rb",
     "spec/support/app/models/user.rb",
     "spec/support/app/views/dashboard/index.erb",
     "spec/support/app/views/session/new.erb",
     "spec/support/config/boot.rb",
     "spec/support/config/database.yml",
     "spec/support/config/pagseguro.yml",
     "spec/support/config/routes.rb",
     "spec/support/log/test.log",
     "spec/support/matcher.rb",
     "spec/support/pagseguro-test.yml",
     "spec/support/tmp/pagseguro-test.yml",
     "templates/config.yml"
  ]
  s.homepage = %q{http://github.com/fnando/pagseguro}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A wrapper for the PagSeguro payment gateway.}
  s.test_files = [
    "spec/controllers/developer_controller_spec.rb",
     "spec/helpers/helper_spec.rb",
     "spec/pagseguro/notification_spec.rb",
     "spec/pagseguro/order_spec.rb",
     "spec/pagseguro/pagseguro_spec.rb",
     "spec/pagseguro/rake_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/app/controllers/application_controller.rb",
     "spec/support/app/models/account.rb",
     "spec/support/app/models/user.rb",
     "spec/support/config/boot.rb",
     "spec/support/config/routes.rb",
     "spec/support/matcher.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
  end
end

